### PR TITLE
fix makepeds geometry and gain deployment after backend change

### PR DESCRIPTION
**Pull request by vespos**
## Description
Fix makepeds gain and geometry deployment

## Motivation and Context
Backend changed messed up the deployment of files from the ffb

## How Has This Been Tested?
xppx1004421 run 1

## Where Has This Been Documented?
N/A

### CODE REVIEW

**Comment by vespos** [comment]
Need to fix the part with the deployment of the gain for the jungfrau. This probably has to be done at the level of the jungfrau_gain_constants function.

**Comment by silkenelson** [comment]
I don't really want to approve this because I feel pretty strongly that the -x argument should take the _same_ information for gain & geometry as it does for pedestal creation.

**Comment by vespos** [comment]
Yes, let's keep it open until we settle on something with Mikhail.

**Comment by vespos** [comment]
I think we can abandon this PR, given that MIkhail has improved things on his side?

**Comment by silkenelson** [comment]
Agreed.

**Pull request closed without merging**
